services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: "./.env"
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
  postgres:
    image: postgres:18-alpine
    container_name: wagering_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_postgres -d wagering_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.8.0
    container_name: wagering_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock

  keycloak:
    image: quay.io/keycloak/keycloak:26.8
    container_name: wagering_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

volumes:
  pgdata:
